name: Machine learning @ Tor Vergata
title: Machine learning
subtitle: CdLM in Informatica - Universita' di Roma Tor Vergata
description: Corso di Machine Learning, CdLM in Informatica - Universita' di Roma Tor Vergata
aa: anno accademico 2024-2025
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
#just-the-docs-0.8.2
author: Giorgio Gambosi
author_email: giorgio.gambosi@uniroma2.it
baseurl: /ml2425
#markdown: rdiscount
permalink: pretty
timezone: Europe/Rome
future: true

category_dir: /
# How many articles do you wish to appear on the front page:
#paginate: 5

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

markdown: kramdown
